export const FETCH_DATA_FAVORITE_PRODUCTS_REQUEST =
  "FETCH_DATA_FAVORITE_PRODUCTS_REQUEST";
export const FETCH_DATA_FAVORITE_PRODUCTS_SUCCESS =
  "FETCH_DATA_FAVORITE_PRODUCTS_SUCCESS";
export const FETCH_DATA_FAVORITE_PRODUCTS_FAILURE =
  "FETCH_DATA_FAVORITE_PRODUCTS_FAILURE";
export const ADD_FAVORITE_PRODUCT = "ADD_FAVORITE_PRODUCT";
export const REMOVE_FAVORITE_PRODUCT = "REMOVE_FAVORITE_PRODUCT";

export const SET_IS_LOADING_BOX = "SET_IS_LOADING_BOX";

export const GET_VIEWED_PRODUCTS = "GET_VIEWED_PRODUCTS";
export const ADD_VIEWED_PRODUCT = "ADD_VIEWED_PRODUCTS";
export const REMOVE_VIEWED_PRODUCT = "REMOVE_VIEWED_PRODUCT";
